"""remove_discount_from_products

Revision ID: c4820b2cd267
Revises: daafbbadf65c
Create Date: 2024-03-26 23:12:16.231996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4820b2cd267'
down_revision: Union[str, None] = 'daafbbadf65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###
