"""remove product_name from sale_products

Revision ID: daafbbadf65c
Revises: ec45f6bd7030
Create Date: 2025-05-26 23:12:16.231996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daafbbadf65c'
down_revision: Union[str, None] = 'ec45f6bd7030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_products', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_products', sa.Column('product_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
